#
b /emc/reale/bi_01/amos/data/amos.b1 f 6144000
b /emc/reale/bi_01/amos/data/amos.b2 f 12582912
b /emc/reale/bi_01/amos/data/amos.b3
#
d "Schema Area":6,64;1 /emc/reale/dat_01/amos/data/amos.d1
#
a /emc/reale/ai_01/amos/data/amos.a1 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a2 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a3 f 2097152
#
d "Gltbls_Data_02":10,64;512 /emc/reale/dat_05/amos/data/amos_10.d1 f 16777216
d "Gltbls_Data_02":10,64;512 /emc/reale/dat_05/amos/data/amos_10.d2 f 16777216
d "Gltbls_Data_02":10,64;512 /emc/reale/dat_05/amos/data/amos_10.d3 f 16777216
d "Gltbls_Data_02":10,64;512 /emc/reale/prod/amos/data/amos_10.d4 f 16777216
d "Gltbls_Data_02":10,64;512 /emc/reale/dat_06/amos/data/amos_10.d5 f 16777216
d "Gltbls_Data_02":10,64;512 /emc/reale/dat_06/amos/data/amos_10.d6 f 16777216
d "Gltbls_Data_02":10,64;512 /emc/reale/dat_06/amos/data/amos_10.d7 f 16777216
d "Gltbls_Data_02":10,64;512 /emc/reale/dat_03/amos/data/amos_10.d8
#
d "Gltbls_Index":11,64;8 /emc/reale/dat_01/amos/data/amos_11.d1 f 2097152
d "Gltbls_Index":11,64;8 /emc/reale/dat_01/amos/data/amos_11.d2 f 8388608
d "Gltbls_Index":11,64;8 /emc/reale/prod/amos/data/amos_11.d3 f 8388608
d "Gltbls_Index":11,64;8 /emc/reale/dat_03/amos/data/amos_11.d4
#
d "PDACTVTY_Data":12,128;512 /emc/reale/dat_02/amos/data/amos_12.d1 f 20971520
d "PDACTVTY_Data":12,128;512 /emc/reale/dat_02/amos/data/amos_12.d2 f 20971520
d "PDACTVTY_Data":12,128;512 /emc/reale/dat_02/amos/data/amos_12.d3
#
d "PDACTVTY_Index":13,1;8 /emc/reale/dat_02/amos/data/amos_13.d1 f 3145728
d "PDACTVTY_Index":13,1;8 /emc/reale/dat_02/amos/data/amos_13.d2 f 361600
d "PDACTVTY_Index":13,1;8 /emc/reale/dat_02/amos/data/amos_13.d3 f 3145728
d "PDACTVTY_Index":13,1;8 /emc/reale/dat_02/amos/data/amos_13.d4 f 3145728
d "PDACTVTY_Index":13,1;8 /emc/reale/dat_02/amos/data/amos_13.d5 f 3145728
d "PDACTVTY_Index":13,1;8 /emc/reale/dat_02/amos/data/amos_13.d6
#
d "PROCCTRL_Data":14,256;64 /emc/reale/dat_03/amos/data/amos_14.d1 f 3145728
d "PROCCTRL_Data":14,256;64 /emc/reale/dat_03/amos/data/amos_14.d2
#
d "PROCCTRL_Index":15,1;8 /emc/reale/dat_03/amos/data/amos_15.d1 f 524288
d "PROCCTRL_Index":15,1;8 /emc/reale/dat_03/amos/data/amos_15.d2
#
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/prod/amos/data/amos_20.d1 f 16777216
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d2 f 8388608
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d3 f 2359424
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d4 f 4194304
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d5 f 729088
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d6 f 16777216
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d7 f 16777216
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d8 f 16777216
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_03/amos/data/amos_20.d9 f 16777216
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/prod/amos/data/amos_20.d10 f 16777216
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_05/amos/data/amos_20.d11 f 16777216
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_04/amos/data/amos_20.d12 f 33554432
d "AMOS_LRGE_DATA_02":20,64;512 /emc/reale/dat_02/amos/data/amos_20.d13
#
a /emc/reale/ai_01/amos/data/amos.a4 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a5 f 2097152
#
d "MAST_SMLL_DATA_01":26,64;8 /emc/reale/prod/amos/data/amos_26.d1 f 2097152
d "MAST_SMLL_DATA_01":26,64;8 /emc/reale/prod/amos/data/amos_26.d2 f 2097152
d "MAST_SMLL_DATA_01":26,64;8 /emc/reale/dat_03/amos/data/amos_26.d3 f 2097152
d "MAST_SMLL_DATA_01":26,64;8 /emc/reale/dat_03/amos/data/amos_26.d4
#
d "REQUEST_DATA_01":27,64;64 /emc/reale/dat_01/amos/data/amos_27.d1 f 2097152
d "REQUEST_DATA_01":27,64;64 /emc/reale/dat_01/amos/data/amos_27.d2 f 2097152
d "REQUEST_DATA_01":27,64;64 /emc/reale/dat_06/amos/data/amos_27.d3 f 2097152
d "REQUEST_DATA_01":27,64;64 /emc/reale/dat_06/amos/data/amos_27.d4 f 4097152
d "REQUEST_DATA_01":27,64;64 /emc/reale/dat_06/amos/data/amos_27.d5 f 4097152
d "REQUEST_DATA_01":27,64;64 /emc/reale/dat_06/amos/data/amos_27.d6
#
a /emc/reale/ai_01/amos/data/amos.a6 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a7 f 2097152
#
d "CRELOG_Data":30,64;512 /emc/reale/prod/amos/data/amos_30.d1 f 2097152
d "CRELOG_Data":30,64;512 /emc/reale/prod/amos/data/amos_30.d2 f 12288
d "CRELOG_Data":30,64;512 /emc/reale/prod/amos/data/amos_30.d3 f 2097152
d "CRELOG_Data":30,64;512 /emc/reale/prod/amos/data/amos_30.d4
#
d "CRELOG_Index":31,64;8 /emc/reale/prod/amos/data/amos_31.d1 f 524288
d "CRELOG_Index":31,64;8 /emc/reale/prod/amos/data/amos_31.d2 f 8388608
d "CRELOG_Index":31,64;8 /emc/reale/prod/amos/data/amos_31.d3
#
d "LOG_SMLL_DATA_03":32,64;512 /emc/reale/prod/amos/data/amos_32.d1 f 8388608
d "LOG_SMLL_DATA_03":32,64;512 /emc/reale/prod/amos/data/amos_32.d2 f 8388608
d "LOG_SMLL_DATA_03":32,64;512 /emc/reale/prod/amos/data/amos_32.d3
#
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_04/amos/data/amos_33.d1 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_04/amos/data/amos_33.d2 f 946176
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_04/amos/data/amos_33.d3 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_01/amos/data/amos_33.d4 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_05/amos/data/amos_33.d5 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_01/amos/data/amos_33.d6 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_02/amos/data/amos_33.d7 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_02/amos/data/amos_33.d8 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_02/amos/data/amos_33.d9 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_06/amos/data/amos_33.d10 f 14680064
d "ACCT_LRGE_DATA_02":33,64;512 /emc/reale/dat_04/amos/data/amos_33.d11
#
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_03/amos/data/amos_34.d1 f 6291456
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_03/amos/data/amos_34.d2 f 2535040
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_03/amos/data/amos_34.d3 f 4194304
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_03/amos/data/amos_34.d4 f 318592
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_03/amos/data/amos_34.d5 f 4194304
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_01/amos/data/amos_34.d6 f 6291456
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_01/amos/data/amos_34.d7 f 6291456
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_01/amos/data/amos_34.d8 f 6291456
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_02/amos/data/amos_34.d9 f 6291456
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_01/amos/data/amos_34.d10 f 6291456
d "ACCT_LRGE_INDEX":34,64;8 /emc/reale/dat_05/amos/data/amos_34.d11
#
d "ETLOANBR_Data":35,64;512 /emc/reale/dat_06/amos/data/amos_35.d1 f 6291456
d "ETLOANBR_Data":35,64;512 /emc/reale/dat_06/amos/data/amos_35.d2 f 6291456
d "ETLOANBR_Data":35,64;512 /emc/reale/dat_03/amos/data/amos_35.d3 f 6291456
d "ETLOANBR_Data":35,64;512 /emc/reale/dat_02/amos/data/amos_35.d4
#
d "ETLOANBR_Index":36,64;8 /emc/reale/dat_06/amos/data/amos_36.d1 f 2097152
d "ETLOANBR_Index":36,64;8 /emc/reale/dat_06/amos/data/amos_36.d2 f 2097152
d "ETLOANBR_Index":36,64;8 /emc/reale/prod/amos/data/amos_36.d3 f 2097152
d "ETLOANBR_Index":36,64;8 /emc/reale/dat_03/amos/data/amos_36.d4
#
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/prod/amos/data/amos_37.d1 f 6291456
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/prod/amos/data/amos_37.d2 f 12288
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/dat_01/amos/data/amos_37.d3 f 4194304
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/dat_01/amos/data/amos_37.d4 f 4096
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/dat_01/amos/data/amos_37.d5 f 8388608
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/dat_01/amos/data/amos_37.d6 f 4096
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/dat_03/amos/data/amos_37.d7 f 8388608
d "ET_LRGE_DATA_02":37,64;512 /emc/reale/dat_01/amos/data/amos_37.d8
#
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d1 f 16777216
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d2 f 4194304
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d3 f 176128
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d4 f 8388608
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d5 f 16777216
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d6 f 16777216
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d7 f 16777216
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d8 f 16777216
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d9 f 16777216
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d10 f 16777216
d "LB_LRGE_DATA_03":38,64;512 /emc/reale/dat_06/amos/data/amos_38.d11
#
a /emc/reale/ai_01/amos/data/amos.a8 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a9 f 2097152
#
d "CRE_INFO_Data":42,64;512 /emc/reale/dat_02/amos/data/amos_42.d1 f 6291456
d "CRE_INFO_Data":42,64;512 /emc/reale/dat_02/amos/data/amos_42.d2 f 2297984
d "CRE_INFO_Data":42,64;512 /emc/reale/dat_02/amos/data/amos_42.d3 f 4194304
d "CRE_INFO_Data":42,64;512 /emc/reale/dat_02/amos/data/amos_42.d4 f 446464
d "CRE_INFO_Data":42,64;512 /emc/reale/dat_03/amos/data/amos_42.d5 f 8388608
d "CRE_INFO_Data":42,64;512 /emc/reale/dat_03/amos/data/amos_42.d6
#
d "CRE_INFO_Index":43,64;8 /emc/reale/dat_02/amos/data/amos_43.d1 f 2097152
d "CRE_INFO_Index":43,64;8 /emc/reale/dat_02/amos/data/amos_43.d2 f 26240
d "CRE_INFO_Index":43,64;8 /emc/reale/dat_02/amos/data/amos_43.d3 f 4194304
d "CRE_INFO_Index":43,64;8 /emc/reale/dat_02/amos/data/amos_43.d4 f 128
d "CRE_INFO_Index":43,64;8 /emc/reale/dat_02/amos/data/amos_43.d5 f 8388608
d "CRE_INFO_Index":43,64;8 /emc/reale/dat_02/amos/data/amos_43.d6
#
d "CRE_LRGE_DATA_03":44,64;512 /emc/reale/dat_04/amos/data/amos_44.d1 f 4194304
d "CRE_LRGE_DATA_03":44,64;512 /emc/reale/dat_04/amos/data/amos_44.d2
#
a /emc/reale/ai_01/amos/data/amos.a10 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a11 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a12 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a13 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a14 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a15 f 2097152
#
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_04/amos/data/amos_55.d1 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_04/amos/data/amos_55.d2 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_02/amos/data/amos_55.d3 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_02/amos/data/amos_55.d4 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_02/amos/data/amos_55.d5 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_05/amos/data/amos_55.d6 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_05/amos/data/amos_55.d7 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_02/amos/data/amos_55.d8 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_04/amos/data/amos_55.d9 f 10485760
d "RUNLOG_Data_01":55,64;512 /emc/reale/dat_03/amos/data/amos_55.d10
#
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_04/amos/data/amos_56.d1 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_04/amos/data/amos_56.d2 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_04/amos/data/amos_56.d3 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_04/amos/data/amos_56.d4 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_06/amos/data/amos_56.d5 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_02/amos/data/amos_56.d6 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_06/amos/data/amos_56.d7 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_02/amos/data/amos_56.d8 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_02/amos/data/amos_56.d9 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_02/amos/data/amos_56.d10 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_03/amos/data/amos_56.d11 f 1048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_05/amos/data/amos_56.d12 f 3048576
d "RUNLOG_Index_01":56,64;8 /emc/reale/dat_01/amos/data/amos_56.d13
#
a /emc/reale/ai_01/amos/data/amos.a16 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a17 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a18 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a19 f 2097152
#
d "FH_DATA_01":61,64;512 /emc/reale/prod/amos/data/amos_61.d1 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_02/amos/data/amos_61.d2 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_05/amos/data/amos_61.d3 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_05/amos/data/amos_61.d4 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_05/amos/data/amos_61.d5 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_06/amos/data/amos_61.d6 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_04/amos/data/amos_61.d7 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_06/amos/data/amos_61.d8 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_04/amos/data/amos_61.d9 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/dat_01/amos/data/amos_61.d10 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/prod/amos/data/amos_61.d11 f 16777216
d "FH_DATA_01":61,64;512 /emc/reale/prod/amos/data/amos_61.d12
#
d "FH_INDEX_01":62,8;8 /emc/reale/prod/amos/data/amos_62.d1 f 16777216
d "FH_INDEX_01":62,8;8 /emc/reale/dat_04/amos/data/amos_62.d2 f 16777216
d "FH_INDEX_01":62,8;8 /emc/reale/dat_05/amos/data/amos_62.d3 f 3196544
d "FH_INDEX_01":62,8;8 /emc/reale/dat_03/amos/data/amos_62.d4 f 16777216
d "FH_INDEX_01":62,8;8 /emc/reale/dat_03/amos/data/amos_62.d5 f 16777216
d "FH_INDEX_01":62,8;8 /emc/reale/dat_02/amos/data/amos_62.d6 f 16777216
d "FH_INDEX_01":62,8;8 /emc/reale/dat_04/amos/data/amos_62.d7 f 16777216
d "FH_INDEX_01":62,8;8 /emc/reale/dat_04/amos/data/amos_62.d8
#
d "AMOS_Alter_BP":65,64;512 /emc/reale/dat_01/amos/data/amos_65.d1 f 2097152
d "AMOS_Alter_BP":65,64;512 /emc/reale/dat_01/amos/data/amos_65.d2
#
a /emc/reale/ai_01/amos/data/amos.a20 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a21 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a22 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a23 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a24 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a25 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a26 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a27 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a28 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a29 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a30 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a31 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a32 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a33 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a34 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a35 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a36 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a37 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a38 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a39 f 2097152
#
a /emc/reale/ai_01/amos/data/amos.a40 f 2097152
#
d "MessageLog_Data_01":107,64;512 /emc/reale/dat_06/amos/data/amos_107.d1 f 6291456
d "MessageLog_Data_01":107,64;512 /emc/reale/dat_06/amos/data/amos_107.d2
#
d "MessageLog_Index_01":108,64;8 /emc/reale/dat_06/amos/data/amos_108.d1 f 524288
d "MessageLog_Index_01":108,64;8 /emc/reale/dat_06/amos/data/amos_108.d2 f 524288
d "MessageLog_Index_01":108,64;8 /emc/reale/dat_02/amos/data/amos_108.d3
#
d "TrnsLog_Data":113,64;512 /emc/reale/dat_03/amos/data/amos_113.d1 f 5242880
d "TrnsLog_Data":113,64;512 /emc/reale/prod/amos/data/amos_113.d2 f 5242880
d "TrnsLog_Data":113,64;512 /emc/reale/dat_01/amos/data/amos_113.d3 f 5242880
d "TrnsLog_Data":113,64;512 /emc/reale/dat_02/amos/data/amos_113.d4 f 5242880
d "TrnsLog_Data":113,64;512 /emc/reale/dat_02/amos/data/amos_113.d5 f 5242880
d "TrnsLog_Data":113,64;512 /emc/reale/dat_03/amos/data/amos_113.d6 f 5242880
d "TrnsLog_Data":113,64;512 /emc/reale/dat_02/amos/data/amos_113.d7 f 5242880
d "TrnsLog_Data":113,64;512 /emc/reale/dat_03/amos/data/amos_113.d8
#
d "TrnsLog_Index":114,64;8 /emc/reale/dat_04/amos/data/amos_114.d1 f 524288
d "TrnsLog_Index":114,64;8 /emc/reale/dat_04/amos/data/amos_114.d2 f 524288
d "TrnsLog_Index":114,64;8 /emc/reale/dat_04/amos/data/amos_114.d3 f 524288
d "TrnsLog_Index":114,64;8 /emc/reale/dat_04/amos/data/amos_114.d4 f 524288
d "TrnsLog_Index":114,64;8 /emc/reale/dat_04/amos/data/amos_114.d5 f 524288
d "TrnsLog_Index":114,64;8 /emc/reale/dat_04/amos/data/amos_114.d6
#
d "FH_DATA_03":115,64;512 /emc/reale/prod/amos/data/amos_115.d1 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/dat_01/amos/data/amos_115.d2 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/dat_04/amos/data/amos_115.d3 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/dat_03/amos/data/amos_115.d4 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/prod/amos/data/amos_115.d5 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/dat_01/amos/data/amos_115.d6 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/dat_01/amos/data/amos_115.d7 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/dat_06/amos/data/amos_115.d8 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/prod/amos/data/amos_115.d9 f 5062656
d "FH_DATA_03":115,64;512 /emc/reale/dat_01/amos/data/amos_115.d10 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/dat_05/amos/data/amos_115.d11 f 8192000
d "FH_DATA_03":115,64;512 /emc/reale/prod/amos/data/amos_115.d12
#
d "FH_INDEX_03":116,8;8 /emc/reale/prod/amos/data/amos_116.d1 f 8192000
d "FH_INDEX_03":116,8;8 /emc/reale/dat_03/amos/data/amos_116.d2 f 8192000
d "FH_INDEX_03":116,8;8 /emc/reale/dat_01/amos/data/amos_116.d3 f 9444480
d "FH_INDEX_03":116,8;8 /emc/reale/dat_04/amos/data/amos_116.d4 f 8192000
d "FH_INDEX_03":116,8;8 /emc/reale/dat_01/amos/data/amos_116.d5 f 9444480
d "FH_INDEX_03":116,8;8 /emc/reale/dat_05/amos/data/amos_116.d6 f 8192000
d "FH_INDEX_03":116,8;8 /emc/reale/dat_05/amos/data/amos_116.d7
#
d "AUDIT_DATA":121,64;512 /emc/reale/prod/amos/data/amos_121.d1 f 2048000
d "AUDIT_DATA":121,64;512 /emc/reale/prod/amos/data/amos_121.d2
#
d "AUDIT_INDEX":122,64;512 /emc/reale/prod/amos/data/amos_122.d1 f 1024000
d "AUDIT_INDEX":122,64;512 /emc/reale/prod/amos/data/amos_122.d2
#
d "AMOS_S128_DATA":123,128;64 /emc/reale/dat_02/amos/data/amos_123.d1 f 4096000
d "AMOS_S128_DATA":123,128;64 /emc/reale/dat_02/amos/data/amos_123.d2
#
d "AMOS_S128_INDEX":124,1;8 /emc/reale/dat_02/amos/data/amos_124.d1 f 2048000
d "AMOS_S128_INDEX":124,1;8 /emc/reale/dat_02/amos/data/amos_124.d2
#
d "AMOS_M128_DATA":125,64;512 /emc/reale/dat_01/amos/data/amos_125.d1 f 16777216
d "AMOS_M128_DATA":125,64;512 /emc/reale/dat_01/amos/data/amos_125.d2 f 16777216
d "AMOS_M128_DATA":125,64;512 /emc/reale/prod/amos/data/amos_125.d3 f 16777216
d "AMOS_M128_DATA":125,64;512 /emc/reale/dat_01/amos/data/amos_125.d4
#
d "AMOS_M128_INDEX":126,1;8 /emc/reale/dat_02/amos/data/amos_126.d1 f 8192000
d "AMOS_M128_INDEX":126,1;8 /emc/reale/dat_02/amos/data/amos_126.d2
#
d "AMOS_L128_DATA":127,128;64 /emc/reale/dat_01/amos/data/amos_127.d1 f 16777216
d "AMOS_L128_DATA":127,128;64 /emc/reale/dat_01/amos/data/amos_127.d2 f 16777216
d "AMOS_L128_DATA":127,128;64 /emc/reale/dat_01/amos/data/amos_127.d3 f 16777216
d "AMOS_L128_DATA":127,128;64 /emc/reale/dat_01/amos/data/amos_127.d4
#
d "AMOS_L128_INDEX":128,1;8 /emc/reale/dat_03/amos/data/amos_128.d1 f 8192000
d "AMOS_L128_INDEX":128,1;8 /emc/reale/dat_03/amos/data/amos_128.d2
#
d "New_data":129,128;64 /emc/reale/dat_01/amos/data/amos_129.d1 f 5242880
d "New_data":129,128;64 /emc/reale/dat_01/amos/data/amos_129.d2
#
d "New_index":130,1;8 /emc/reale/dat_03/amos/data/amos_130.d1 f 5242880
d "New_index":130,1;8 /emc/reale/dat_03/amos/data/amos_130.d2
#
d "xNewxcomm_data":131,64;512 /emc/reale/dat_01/amos/data/amos_131.d1 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_01/amos/data/amos_131.d2 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_02/amos/data/amos_131.d3 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_02/amos/data/amos_131.d4 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_02/amos/data/amos_131.d5 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_02/amos/data/amos_131.d6 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_03/amos/data/amos_131.d7 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_03/amos/data/amos_131.d8 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_03/amos/data/amos_131.d9 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_04/amos/data/amos_131.d10 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_04/amos/data/amos_131.d11 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_04/amos/data/amos_131.d12 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_05/amos/data/amos_131.d13 f 33554432
d "xNewxcomm_data":131,64;512 /emc/reale/dat_05/amos/data/amos_131.d14
#
d "xNewxcomm_index":132,1;8 /emc/reale/dat_05/amos/data/amos_132.d1 f 33554432
d "xNewxcomm_index":132,1;8 /emc/reale/dat_05/amos/data/amos_132.d2 f 33554432
d "xNewxcomm_index":132,1;8 /emc/reale/dat_05/amos/data/amos_132.d3 f 33554432
d "xNewxcomm_index":132,1;8 /emc/reale/prod/amos/data/amos_132.d4 f 33554432
d "xNewxcomm_index":132,1;8 /emc/reale/dat_01/amos/data/amos_132.d5 f 33554432
d "xNewxcomm_index":132,1;8 /emc/reale/dat_05/amos/data/amos_132.d6
#
d "xcomm_data":133,64;512 /emc/reale/dat_06/amos/data/amos_133.d1 f 33554432
d "xcomm_data":133,64;512 /emc/reale/dat_06/amos/data/amos_133.d2 f 33554432
d "xcomm_data":133,64;512 /emc/reale/dat_06/amos/data/amos_133.d3 f 33554432
d "xcomm_data":133,64;512 /emc/reale/prod/amos/data/amos_133.d4 f 33554432
d "xcomm_data":133,64;512 /emc/reale/prod/amos/data/amos_133.d5 f 33554432
d "xcomm_data":133,64;512 /emc/reale/dat_03/amos/data/amos_133.d6 f 33554432
d "xcomm_data":133,64;512 /emc/reale/dat_03/amos/data/amos_133.d7
#
d "xcomm_index":134,1;8 /emc/reale/prod/amos/data/amos_134.d1 f 33554432
d "xcomm_index":134,1;8 /emc/reale/prod/amos/data/amos_134.d2 f 604288
d "xcomm_index":134,1;8 /emc/reale/prod/amos/data/amos_134.d3 f 17775744
d "xcomm_index":134,1;8 /emc/reale/dat_05/amos/data/amos_134.d4 f 33554432
d "xcomm_index":134,1;8 /emc/reale/dat_04/amos/data/amos_134.d5 f 33554432
d "xcomm_index":134,1;8 /emc/reale/dat_05/amos/data/amos_134.d6
#
d "FH_DATA_02":135,64;512 /emc/reale/dat_01/amos/data/amos_135.d1 f 33554432
d "FH_DATA_02":135,64;512 /emc/reale/dat_01/amos/data/amos_135.d2 f 33554432
d "FH_DATA_02":135,64;512 /emc/reale/dat_06/amos/data/amos_135.d3 f 33554432
d "FH_DATA_02":135,64;512 /emc/reale/dat_06/amos/data/amos_135.d4
#
d "FH_INDEX_02":136,8;8 /emc/reale/dat_04/amos/data/amos_136.d1 f 33554432
d "FH_INDEX_02":136,8;8 /emc/reale/dat_04/amos/data/amos_136.d2 f 2652800
d "FH_INDEX_02":136,8;8 /emc/reale/prod/amos/data/amos_136.d3 f 8388608
d "FH_INDEX_02":136,8;8 /emc/reale/prod/amos/data/amos_136.d4
#
d "FH_DATA_05":137,64;512 /emc/reale/dat_05/amos/data/amos_137.d1 f 33554432
d "FH_DATA_05":137,64;512 /emc/reale/dat_05/amos/data/amos_137.d2 f 33554432
d "FH_DATA_05":137,64;512 /emc/reale/dat_05/amos/data/amos_137.d3 f 33554432
d "FH_DATA_05":137,64;512 /emc/reale/dat_05/amos/data/amos_137.d4 f 33554432
d "FH_DATA_05":137,64;512 /emc/reale/dat_01/amos/data/amos_137.d5 f 33554432
d "FH_DATA_05":137,64;512 /emc/reale/dat_04/amos/data/amos_137.d6 f 33554432
d "FH_DATA_05":137,64;512 /emc/reale/dat_06/amos/data/amos_137.d7
#
d "FH_INDEX_05":138,8;8 /emc/reale/dat_05/amos/data/amos_138.d1 f 33554432
d "FH_INDEX_05":138,8;8 /emc/reale/dat_05/amos/data/amos_138.d2 f 33554432
d "FH_INDEX_05":138,8;8 /emc/reale/dat_04/amos/data/amos_138.d3 f 33554432
d "FH_INDEX_05":138,8;8 /emc/reale/dat_05/amos/data/amos_138.d4
#
d "mdmvr_data":139,64;512 /emc/reale/dat_05/amos/data/amos_139.d1 f 33554432
d "mdmvr_data":139,64;512 /emc/reale/dat_06/amos/data/amos_139.d2 f 33554432
d "mdmvr_data":139,64;512 /emc/reale/dat_05/amos/data/amos_139.d3
#
d "mdmvr_index":140,1;8 /emc/reale/dat_04/amos/data/amos_140.d1 f 33554432
d "mdmvr_index":140,1;8 /emc/reale/dat_05/amos/data/amos_140.d2
#
d "mdmuplog_data":141,64;512 /emc/reale/prod/amos/data/amos_141.d1 f 33554432
d "mdmuplog_data":141,64;512 /emc/reale/dat_06/amos/data/amos_141.d2 f 33554432
d "mdmuplog_data":141,64;512 /emc/reale/dat_05/amos/data/amos_141.d3
#
d "mdmuplog_index":142,1;8 /emc/reale/dat_04/amos/data/amos_142.d1 f 33554432
d "mdmuplog_index":142,1;8 /emc/reale/dat_05/amos/data/amos_142.d2
#
d "rstg_data":143,64;512 /emc/reale/dat_01/amos/data/amos_143.d1 f 8192000
d "rstg_data":143,64;512 /emc/reale/dat_05/amos/data/amos_143.d2
#
d "rstg_index":144,1;8 /emc/reale/dat_01/amos/data/amos_144.d1 f 5242880
d "rstg_index":144,1;8 /emc/reale/dat_05/amos/data/amos_144.d2
